### ISSUE TITLE
LICENSE.md is missing

### ISSUE THREAD

**Issue by Hint10** [navalgandhi1989/-ckeditor-autocomplete-suggestions-plugin#4]
I want to use this awesome plugin, but I can't find any licence terms and I'm not sure under which licence it is. CKEditor itself is under GPL, LGPL, MPL - does this also apply to the plugin?

**Comment by navalgandhi1989** [comment]
Hi,

The plugin is open source and free to use. Its was more of a hobby project for me. 

Best of luck for your application.
